// <auto-generated />
using System;
using MedicalEquipmentMarket.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MedicalEquipmentMarket.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.24")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MedicalEquipmentMarket.Model.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Company");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Beogradska 26",
                            City = "Beograd",
                            Name = "Beomed",
                            PhoneNumber = "021731524"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Bulevar Mihajla Pupina 25",
                            City = "Novi Sad",
                            Name = "Health&Care",
                            PhoneNumber = "021731522"
                        },
                        new
                        {
                            Id = 3,
                            Address = "Futoski put 12",
                            City = "Novi Sad",
                            Name = "Galenika",
                            PhoneNumber = "021731511"
                        });
                });

            modelBuilder.Entity("MedicalEquipmentMarket.Model.Equipment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Equipment");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Aparat za osluskivanja rada pluca i srca",
                            Name = "Stetoskop",
                            Price = 20000.0
                        },
                        new
                        {
                            Id = 2,
                            Description = "Namestaj za pacijente",
                            Name = "Krevet",
                            Price = 14000.0
                        },
                        new
                        {
                            Id = 3,
                            Description = "Oprema za previjanje",
                            Name = "Pakovanje zavoja",
                            Price = 1200.0
                        });
                });

            modelBuilder.Entity("MedicalEquipmentMarket.Model.Reservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BuyerAccountId")
                        .HasColumnType("integer");

                    b.Property<int>("CompanyId")
                        .HasColumnType("integer");

                    b.Property<int>("EquipmentId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ReservationTime")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Reservation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BuyerAccountId = 1,
                            CompanyId = 2,
                            EquipmentId = 2,
                            ReservationTime = new DateTime(2023, 11, 18, 17, 17, 11, 963, DateTimeKind.Utc).AddTicks(8051)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
